// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH68stPZA58I-y-4XTHCHK57aS1NoxfQg',
    appId: '1:484026167704:web:6ed218cb9d57f6d139bbed',
    messagingSenderId: '484026167704',
    projectId: 'crud-app-3c24f',
    authDomain: 'crud-app-3c24f.firebaseapp.com',
    databaseURL: 'https://crud-app-3c24f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-app-3c24f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTSILs6HU4q-U8O9gkiZNmePqPADluJM8',
    appId: '1:484026167704:android:35df57cea005047339bbed',
    messagingSenderId: '484026167704',
    projectId: 'crud-app-3c24f',
    databaseURL: 'https://crud-app-3c24f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-app-3c24f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMiJSwbWBQj3LiI9Ku3otOdl3lzM6P6NM',
    appId: '1:484026167704:ios:8c7b67987f3c06d739bbed',
    messagingSenderId: '484026167704',
    projectId: 'crud-app-3c24f',
    databaseURL: 'https://crud-app-3c24f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-app-3c24f.firebasestorage.app',
    androidClientId: '484026167704-et1ihkm666plkl1qtskna0d4avebala6.apps.googleusercontent.com',
    iosClientId: '484026167704-osqdrv33m6j149km5m9uqevjhtv9sa46.apps.googleusercontent.com',
    iosBundleId: 'project.com.project',
  );

}